name: Build
on: [push, pull_request]
jobs:
  #
  # Build binaries
  #
  build_linux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: make test
    - name: Build
      run: OUT=cronedit-linux make build
    - name: Store binary
      uses: actions/upload-artifact@v2
      with:
        name: cronedit-linux
        path: bin/cronedit-linux
  build_macos:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: make test
    - name: Build
      run: OUT=cronedit-macos make build
    - name: Store binary
      uses: actions/upload-artifact@v2
      with:
        name: cronedit-macos
        path: bin/cronedit-macos
  #
  # Prepare a release if current commit is tagged
  #
  create_release:
    runs-on: ubuntu-18.04
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build_linux, build_macos]
    steps:
      # Draft
      - name: Create release draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
      # cronedit-linux
      - name: Download cronedit-linux
        uses: actions/download-artifact@v2
        with:
          name: cronedit-linux
          path: .
      - name: Upload cronedit-linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./cronedit-linux
          asset_name: cronedit-linux
          asset_content_type: application/octet-stream
      # cronedit-macos
      - name: Download cronedit-macos
        uses: actions/download-artifact@v2
        with:
          name: cronedit-macos
          path: .
      - name: Upload cronedit-macos
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./cronedit-macos
          asset_name: cronedit-macos
          asset_content_type: application/octet-stream
